spring.application.name=demo

# PostgreSQL Connection Settings
# DHAYAN DEIN: Yahan se double 'spring.datasource.url=' hata diya gaya hai


# 1. The URL (Must NOT contain username or password)
spring.datasource.url=jdbc:postgresql://ep-ancient-shape-aoieq4n1.c-2.ap-southeast-1.aws.neon.tech/neondb?sslmode=require

# 2. The Username
spring.datasource.username=neondb_owner

# 3. The Password (No 'jdbc:' prefix here, just the password)
spring.datasource.password=npg_OZR10oIXShyq
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate Settings
# Dialect specify karna ab zaroori nahi hai, Spring khud detect kar leta hai
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

server.port=8081
spring.web.resources.static-locations=classpath:/static/

# JWT Configuration
infonest.jwt.secret=MySuperSecretKeyForInfoNestProject2025MakeItLonger
infonest.jwt.expiration=86400000

# Logging & Mail Settings
logging.level.org.springframework.security=DEBUG
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=suhasinisingh015@gmail.com
spring.mail.password=xetaoffgzesijhzn
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# File Upload Settings
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB